### ISSUE TITLE
Add support for VS 2022

### ISSUE THREAD

**Issue by Tim-Maes** [Tim-Maes/T4Editor#1]

**Comment by mhov** [comment]
Hoping it's just an extension meta data thing.

**Comment by Tim-Maes** [comment]
For previous Visual Studio versions this was the case, and for extensions without running code this is still the case.
But in order to update T4Executer and T4Editor for Visual Studio 2022 and it's editions this requires a different approach as seen [here ](https://docs.microsoft.com/en-us/visualstudio/extensibility/migration/update-visual-studio-extension?view=vs-2022).

Taking a stab at it in the next few days.

Edit: Appareantly T4Editor does not have any 'running code'. Managed to upgrade and test very easily.

**Comment by Tim-Maes** [comment]
Managed to migrate T4Executer - working on this now.

**Comment by Tim-Maes** [comment]
Finished migrating T4Editor - publishing right now on the marketplace. Issue will be closed when I commit the updated code here.
Please download version 2.0.2 from the Marketplace and open an issue if you encounter any bugs or broken features while using T4Editor in VS2022.

Thank you for your patience!
