### ISSUE TITLE
Nice to have: Defaults for light/dark VS theme's

### ISSUE THREAD

**Issue by Tim-Maes** [Tim-Maes/T4Editor#10]
Default colorization settings are based on a dark IDE theme. When a user installs the extension on a light IDE, the default text colors are too light/bright on a white background.

A nice to have would be default settings for both themes, some sort of detection on install or ask the user on first install what defaults are preferred.

**Comment by kc-bell-awardco** [comment]
Agreed, this was a pain for me today when I first installed. I just decided to go with something else rather than have to convert each color individually

**Comment by Tim-Maes** [comment]
As mentioned in issue #11 I have a temporary solution for this. Though, the default colors I set for light theme might not be suitable for everyone since coloring is subjective - so you might have to assign your own colors but this will get rid of the white-on-white issue when installing.
