### ISSUE TITLE
Visual Studio 2022, v17.2.6: No way to adjust text block colors, template text white on white

### ISSUE THREAD

**Issue by paul-michalik** [Tim-Maes/T4Editor#11]
No way to adjust text colors no (Extensions -> T4Editor -> Colors) menu. Color of the text template is white on white.

**Comment by Tim-Maes** [comment]
Hey Paul, do you still have this problem? I tested on 17.2 and 17.4 without any issues.

**Comment by LexaGV** [comment]
On my clear VS 2022 v17.6.4 the extension writes white above white. It's ridiculous! And on my try EXTENSIONS->T4 Editor->Adjust Colors I got childish "Object reference not set to an instance of an object". NRE? Serious?
If you screw up normal experience w "white theme", at least make sure current VS theme is dark! It's total nonsense how people try to be "unique", making enormous dark colors.

**Comment by Tim-Maes** [comment]
I took a quick try at a (temporary) solution for this. This extension was made for personal use first with dark IDE in mind.

On first install, a dialog will be shown where you can specify what theme you are using, and the default colors will adjust based on your choice.

A better solution is too auto-detect the VS theme on initialization. - Will implement this when I have more spare time to invest.

I will release in a few hours.

Kind regards
