### ISSUE TITLE
Wrong standard control blocks (<# ... #>) detection if in touch with double-quote (") symbol

### ISSUE THREAD

**Issue by KirillBorunov** [Tim-Maes/T4Editor#12]
There is a problem when a standard control block open tag `<#` or close tag `#>` is in touch with the double-quote character `"` on any side of any of the tags. The result is the color is not set for this code block it is colored as the result (white by default on my dark theme).
The problem seems to affect only the standard control blocks `<# ... #>` or as you call it on the config window "Statements blocks".
I not tested on other themes than the dark.

To demonstrate the problem I attach a T4 Text Template and its output.
You need to open this file on the Visual Studio with the T4Editor extension installed.
You will see the color inconsistency related to the double-quote symbol.
If you don't want to open it in VS, I added the comments for each case. "WRONG" means it is colored as result (white by default on my dark theme) instead of as code.

I also included the execution result to demonstrate that the template will execute as expected and will not ignore the tags in touch with double-quote characters as the color information suggests.

TextTemplate.tt
```
//Tests with no quotes
//<# #>	<- Displays ok

//Tests with double quotes:
//"<# #>"	<- Displays WRONG!
//" <# #> "	<- Displays ok
//"<# #>	<- Displays WRONG!
//" <# #>	<- Displays ok
//<# #>"	<- Displays WRONG!
//<# #> "	<- Displays ok

//Tests with other quotes/tildes:
//'<# #>'	<- Displays ok
//´<# #>´	<- Displays ok
//`<# #>`	<- Displays ok
//¨<# #>¨	<- Displays ok
```

Result:
```CSharp
//Tests with no quotes
//	<- Displays ok

//Tests with double quotes:
//""	<- Displays WRONG!
//"  "	<- Displays ok
//"	<- Displays WRONG!
//" 	<- Displays ok
//"	<- Displays WRONG!
// "	<- Displays ok

//Tests with other quotes/tildes:
//''	<- Displays ok
//´´	<- Displays ok
//``	<- Displays ok
//¨¨	<- Displays ok
```

Screenshot on my VS with dark theme:
![image](https://user-images.githubusercontent.com/21219388/183542113-a52da6f8-01db-44e3-9e87-38cfdd142e9c.png)

**Comment by Tim-Maes** [comment]
Hi Kirill,

I am fixing this today., thanks for reporting this.

**Comment by Tim-Maes** [comment]
Currently testing. 

![image](https://user-images.githubusercontent.com/91606949/185363635-83bcb981-af78-461d-8b61-d63087496848.png)
