### ISSUE TITLE
Unable to uninstall the extension

### ISSUE THREAD

**Issue by InteXX** [Tim-Maes/T4Editor#15]
I'm trying to uninstall the extension in VS 2022, but it persists after a restart.

Can you assist?

**Comment by Tim-Maes** [comment]
I tried to replicate this issue on several versions of Visual Studio.

`Extensions > Manage > Installed > T4Editor > Uninstall` and this seems to work for me and my collegues.

**Comment by InteXX** [comment]
I checked just now and it's gone. I'm not sure what happened.

There've been a couple of OS reboots since my original report, so that may have cleared something out.

Thanks for your reply. All is well.
