### ISSUE TITLE
Special unicode character breaks coloring

### ISSUE THREAD

**Issue by SolidSoils** [Tim-Maes/T4Editor#2]
This piece of code was not processed properly:

```
<#+
static string CreateSummaryText(string s)
{
    return s.Length < 51 ? s : "…";
}
#>
```

The ellipsis is the culprit here.

**Comment by Tim-Maes** [comment]
Hi SolidSoils, thanks for reporting this issue.

It seems that unicode characters can break coloring, I have updated the filters for all code blocks to include \u2000-\u206F\u2E00-\u2E7F characters and this resolves the issue.

**Comment by Tim-Maes** [comment]
Release 2.1 is being deployed. Please download the latest version from the market place. 

Thank you.
