### ISSUE TITLE
Performance issues with T4Classifier's regular expressions 

### ISSUE THREAD

**Issue by daiplusplus** [Tim-Maes/T4Editor#21]
(This doesn't seem to be the same issue as https://github.com/Tim-Maes/T4Editor/issues/16)

I had a T4 file open and just held-down the spacebar in the editor and experienced performance issues (high CPU, slow VS editor updates, etc) so I started a profiler session and I see that the regular-expressions in `T4Classifier.GetClassificationSpans` were being evaluated via the regex interpreter instead of being compiled in-memory.

![image](https://github.com/Tim-Maes/T4Editor/assets/1693078/d3ecce83-8153-4b27-9f0f-1a46ae1747b6)

![image](https://github.com/Tim-Maes/T4Editor/assets/1693078/954132c9-82c7-4b49-aef0-6477e12bd92a)

----

I'm confident that converting the regexs in `T4Classifier.cs` to be precompiled should provide an immediate perf. boost here, though I'm not currently able to test this hypothesis.

To do this, hide the `const String` patterns as `private` (so other code can't accidentally call non-compiled versions) and use `RegexOptions.Compiled`  (though there are some gotchas too: https://stackoverflow.com/questions/40953573/why-does-the-c-sharp-regexoptions-compiled-makes-the-match-slower )

----

Also, as the regex patterns are `const String` values, you can improve your dev UX by adding `/* language=regex */` [right before the literal](https://stackoverflow.com/questions/63639758/how-does-visual-studio-syntax-highlight-strings-in-the-regex-constructor). The literals look like they could be converted to verbatim literals which makes them more readable as it eliminates the escaped backslashes, like so:

```csharp
internal const string ControlBlockRegex = /* language=regex */ @"(?<openingtag>(?<!\")<#((?!\"|=|@|\+)))(?<code>((?!(?!)<#(?!\+|=)|#>)[\s|\w|\d|\n|().,<>\-:;@#$%^&=*\[\]\"'+\/\®°⁰!?{}|`~\\u2000-\\u206F\\u2E00-\\u2E7F])*)(?<closingtag>(?=\s?|\w?|\n?)(?<!\")#>(?!\"))";
```

**Comment by daiplusplus** [comment]
I've made a quick-and-dirty PR that _should_ hopefully improve things: https://github.com/Tim-Maes/T4Editor/pull/22

**Comment by daiplusplus** [comment]
BTW, as an alternative approach, this extension should probably just use the official T4 parser in VS instead of reinventing the wheel.

There's a high-perf (and annotated!) regex in ` Microsoft.VisualStudio.TextTemplating.TemplateParser.templateParsingRegex` in `C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VisualStudio\v16.0\TextTemplating\Microsoft.VisualStudio.TextTemplating.15.0.dll`:


```

const String VS_OFFICIAL_PATTERN = @"
			# We check if we have an even number of \ in the beginning of	#
			# of the file preceeding an open tag. If we do, then it's		#
			# boilerplate text. We check this in the very beginning because	#
			# if not, the directives/classfeatures etc will match it and we	#
			# won't get the initial backslashes as boilerplate code			#
			(?<boilerplate>^(\\\\)+)(?=<\#)|

			# Check for an unescaped (0 or even number of \ preceeding		#
			# it) directive start tag and it's accompanying end tag. Store	#
			# text of the directive tag in a group named directive			#
			(?<=([^\\]|^)(\\\\)*)<\#@(?<directive>.*?)(?<=[^\\](\\\\)*)\#>|

			# Check for an unescaped classfeature start tag and its end tag	#
			# Store the text between the tags in group called classfeatures	#
			(?<=([^\\]|^)(\\\\)*)<\#\+(?<classfeature>.*?)(?<=[^\\](\\\\)*)\#>|

			# Check for an unescaped expression start tag and its end tag.	#
			# Store the text between the tags in group called expression	#
			(?<=([^\\]|^)(\\\\)*)<\#=(?<expression>.*?)(?<=[^\\](\\\\)*)\#>|

			# Check for an unescaped statement start tag and its end tag.	#
			# Store the text between the tags in group called statement.	#
			# We can only check for statements after checking for			#
			# directives, expressions and classfeatures because the start	#
			# tag for statements is a substring of the other start tags		#
			(?<=([^\\]|^)(\\\\)*)<\#(?<statement>.*?)(?<=[^\\](\\\\)*)\#>|

			# Finally, check for boilerplate code that's not within a start	#
			# or end tag (look for anything preceeding a start tag or an	#
			# EOL) This has to be done at the ver end so that the .+ does	#
			# not match other blocks										#
			(?<boilerplate>.+?)(?=((?<=[^\\](\\\\)*)<\#))|
			(?<boilerplate>.+)(?=$)";
	
const RegexOptions VS_OFFICIAL_PATTERN_OPTS = RegexOptions.ExplicitCapture | RegexOptions.Compiled | RegexOptions.Singleline | RegexOptions.IgnorePatternWhitespace;
```

With the comments removed and converting it to a C# verbatim string literal it reduces down to just this:

```csharp
const String VS_OFFICIAL_PATTERN_CLEANER = @"
(?<boilerplate>^(\\)+)(?=<\#)|
(?<=([^\\]|^)(\\)*)<\#@(?<directive>.*?)(?<=[^\\](\\)*)\#>|
(?<=([^\\]|^)(\\)*)<\#\+(?<classfeature>.*?)(?<=[^\\](\\)*)\#>|
(?<=([^\\]|^)(\\)*)<\#=(?<expression>.*?)(?<=[^\\](\\)*)\#>|
(?<=([^\\]|^)(\\)*)<\#(?<statement>.*?)(?<=[^\\](\\)*)\#>|
(?<boilerplate>.+?)(?=((?<=[^\\](\\)*)<\#))|
(?<boilerplate>.+)(?=$)";
```

It seems to work fine in regex101.com's .NET mode: https://regex101.com/r/GOPSXC/1

**Comment by Tim-Maes** [comment]
Thank you - when I created this extension I was still learning a lot of things including RegEx, I had fun trying to figure these out myself! Using the official pattern is a improvement indeed and I will implement this soon(-ish). 

Appreciate your feedback and time!
