### ISSUE TITLE
Closing characters at end of file colored black (in tt, t4, ttinclude)

### ISSUE THREAD

**Issue by ipavel83** [Tim-Maes/T4Editor#4]
![bug_include_tt](https://user-images.githubusercontent.com/10577825/146688145-9b5fedda-2530-438b-a5a5-45a285fe0b94.png)
[bug.ttinclude.txt](https://github.com/Tim-Maes/T4Editor/files/7741423/bug.ttinclude.txt)

**Comment by Tim-Maes** [comment]
Hi ipavel83

Thanks for reporting this issue. I can reproduce it on basically every T4 file: 

The filter to colorize the output blocks is looking for the next opening <# tag after closing the <#= expression block #>. In your template, it ends with output that is not followed by a new code block. Adding <# #> at the end of file is a temporary workaround to keep it colorized.

I will update the filter to continue colorizing output blocks when they continue until end of file.

**Comment by Tim-Maes** [comment]
Tested, released and deployed (v2.2) on the Visual Studio Marketplace. 

![image](https://user-images.githubusercontent.com/91606949/146738267-f2fdbb34-e97a-48f8-b829-8ee0cf3c349a.png)
