### ISSUE TITLE
Syntax Highlight

### ISSUE THREAD

**Issue by b4eam** [Tim-Maes/T4Editor#9]
**Scenario 1)** Highlighting is disabled for something like: `"<#= something() #>"`. Using a space after #> `"<#= something() #> "` highlighting works correctly - but (of course) produces different output. Where do I need a `"` in code? For generating strings to be used as test data.
**Scenario 2)** Highlighting is disabled and error is thrown for `'..\<#= Path.Combine(root, relative) #>'` but works with `'..\ <#= Path.Combine(root, relative) #>'` (a space between the backslash and <. Using this case for generating test data and comments. FYI - the error information is misleading by indicating to a total different point in code. 

 Would be nice if you can correct this small issue for better readability. Thank you for your work so far!

**Comment by Tim-Maes** [comment]
This is a probably a small bug in the RegEx I use for filtering out codeblocks. The regex does filter out <# #> tags and everything between them, but if it is in between quotation marks as in `var string = "<#";` the regex should not treat it as the end/start of a code block. 

Now adding a space confuses the RegEx. Great excercise for me, I'll look into this.

**Comment by b4eam** [comment]
**Thank you**. I can recommend http://regexstorm.net/tester and https://www.rexegg.com/regex-tricks.html saved me many hours, too. ;)

**Comment by Tim-Maes** [comment]
Would it be possible to provide a example T4 file for me to replicate and test serveral cases?

**Comment by b4eam** [comment]
Sure. The two cases described attached:
[TestCase1.txt](https://github.com/Tim-Maes/T4Editor/files/4052784/TestCase1.txt)
[TestCase2.txt](https://github.com/Tim-Maes/T4Editor/files/4052785/TestCase2.txt)

- Case 1 produces an error that is gone if `'..\<#=` is written as `'..\ <#=` (with a space after the backslash
- Case 2 addresses the highlighting problem

**Comment by Tim-Maes** [comment]
I am working on it. 

I noticed, that if you replace `...\<#=` with `...\\<#=` (escape) it also removes the error and outputs the expecteed result.

**Comment by Tim-Maes** [comment]
Building newest version right now. The syntax highlighting issue has been resolved, please update the latest version.

Still looking into the backslash issue.
